# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'setup.py'
      - 'setup.cfg'
      - 'requirements-dev.txt'
      - 'MANIFEST.in'
      - 'Img/'
      - 'License'
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'License'
      - 'README.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]


    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install -e .
      - name: Check formatted with black
        run: |
          black --check c_formatter_42 tests
      - name: Lint with flake8
        run: |
          flake8 c_formatter_42
          flake8 --extend-ignore=W191,E101,E501 tests
      - name: Test with pytest
        run: |
          pytest -vvv
      - name: Static type checking with mypy
        run: |
          mypy c_formatter_42
